namespace MaaAahwanam.Repository.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class migrations_date_12062017 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.VendorsBeautyServices", "name", c => c.String());
            AddColumn("dbo.VendorsBeautyServices", "Address", c => c.String());
            AddColumn("dbo.VendorsBeautyServices", "Landmark", c => c.String());
            AddColumn("dbo.VendorsBeautyServices", "City", c => c.String());
            AddColumn("dbo.VendorsBeautyServices", "State", c => c.String());
            AddColumn("dbo.VendorsBeautyServices", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsCaterings", "name", c => c.String());
            AddColumn("dbo.VendorsCaterings", "Address", c => c.String());
            AddColumn("dbo.VendorsCaterings", "Landmark", c => c.String());
            AddColumn("dbo.VendorsCaterings", "City", c => c.String());
            AddColumn("dbo.VendorsCaterings", "State", c => c.String());
            AddColumn("dbo.VendorsCaterings", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsDecorators", "name", c => c.String());
            AddColumn("dbo.VendorsDecorators", "Address", c => c.String());
            AddColumn("dbo.VendorsDecorators", "Landmark", c => c.String());
            AddColumn("dbo.VendorsDecorators", "City", c => c.String());
            AddColumn("dbo.VendorsDecorators", "State", c => c.String());
            AddColumn("dbo.VendorsDecorators", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsEntertainments", "name", c => c.String());
            AddColumn("dbo.VendorsEntertainments", "Address", c => c.String());
            AddColumn("dbo.VendorsEntertainments", "Landmark", c => c.String());
            AddColumn("dbo.VendorsEntertainments", "City", c => c.String());
            AddColumn("dbo.VendorsEntertainments", "State", c => c.String());
            AddColumn("dbo.VendorsEntertainments", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsEventOrganisers", "name", c => c.String());
            AddColumn("dbo.VendorsEventOrganisers", "Address", c => c.String());
            AddColumn("dbo.VendorsEventOrganisers", "Landmark", c => c.String());
            AddColumn("dbo.VendorsEventOrganisers", "City", c => c.String());
            AddColumn("dbo.VendorsEventOrganisers", "State", c => c.String());
            AddColumn("dbo.VendorsEventOrganisers", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsGifts", "name", c => c.String());
            AddColumn("dbo.VendorsGifts", "Address", c => c.String());
            AddColumn("dbo.VendorsGifts", "Landmark", c => c.String());
            AddColumn("dbo.VendorsGifts", "City", c => c.String());
            AddColumn("dbo.VendorsGifts", "State", c => c.String());
            AddColumn("dbo.VendorsGifts", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsInvitationCards", "name", c => c.String());
            AddColumn("dbo.VendorsInvitationCards", "Address", c => c.String());
            AddColumn("dbo.VendorsInvitationCards", "Landmark", c => c.String());
            AddColumn("dbo.VendorsInvitationCards", "City", c => c.String());
            AddColumn("dbo.VendorsInvitationCards", "State", c => c.String());
            AddColumn("dbo.VendorsInvitationCards", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsOthers", "name", c => c.String());
            AddColumn("dbo.VendorsOthers", "Address", c => c.String());
            AddColumn("dbo.VendorsOthers", "Landmark", c => c.String());
            AddColumn("dbo.VendorsOthers", "City", c => c.String());
            AddColumn("dbo.VendorsOthers", "State", c => c.String());
            AddColumn("dbo.VendorsOthers", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsPhotographies", "name", c => c.String());
            AddColumn("dbo.VendorsPhotographies", "Address", c => c.String());
            AddColumn("dbo.VendorsPhotographies", "Landmark", c => c.String());
            AddColumn("dbo.VendorsPhotographies", "City", c => c.String());
            AddColumn("dbo.VendorsPhotographies", "State", c => c.String());
            AddColumn("dbo.VendorsPhotographies", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsTravelandAccomodations", "name", c => c.String());
            AddColumn("dbo.VendorsTravelandAccomodations", "Address", c => c.String());
            AddColumn("dbo.VendorsTravelandAccomodations", "Landmark", c => c.String());
            AddColumn("dbo.VendorsTravelandAccomodations", "City", c => c.String());
            AddColumn("dbo.VendorsTravelandAccomodations", "State", c => c.String());
            AddColumn("dbo.VendorsTravelandAccomodations", "ZipCode", c => c.String());
            AddColumn("dbo.VendorsWeddingCollections", "name", c => c.String());
            AddColumn("dbo.VendorsWeddingCollections", "Address", c => c.String());
            AddColumn("dbo.VendorsWeddingCollections", "Landmark", c => c.String());
            AddColumn("dbo.VendorsWeddingCollections", "City", c => c.String());
            AddColumn("dbo.VendorsWeddingCollections", "State", c => c.String());
            AddColumn("dbo.VendorsWeddingCollections", "ZipCode", c => c.String());
            AddColumn("dbo.VendorVenues", "name", c => c.String());
            AddColumn("dbo.VendorVenues", "Address", c => c.String());
            AddColumn("dbo.VendorVenues", "Landmark", c => c.String());
            AddColumn("dbo.VendorVenues", "City", c => c.String());
            AddColumn("dbo.VendorVenues", "State", c => c.String());
            AddColumn("dbo.VendorVenues", "ZipCode", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.VendorVenues", "ZipCode");
            DropColumn("dbo.VendorVenues", "State");
            DropColumn("dbo.VendorVenues", "City");
            DropColumn("dbo.VendorVenues", "Landmark");
            DropColumn("dbo.VendorVenues", "Address");
            DropColumn("dbo.VendorVenues", "name");
            DropColumn("dbo.VendorsWeddingCollections", "ZipCode");
            DropColumn("dbo.VendorsWeddingCollections", "State");
            DropColumn("dbo.VendorsWeddingCollections", "City");
            DropColumn("dbo.VendorsWeddingCollections", "Landmark");
            DropColumn("dbo.VendorsWeddingCollections", "Address");
            DropColumn("dbo.VendorsWeddingCollections", "name");
            DropColumn("dbo.VendorsTravelandAccomodations", "ZipCode");
            DropColumn("dbo.VendorsTravelandAccomodations", "State");
            DropColumn("dbo.VendorsTravelandAccomodations", "City");
            DropColumn("dbo.VendorsTravelandAccomodations", "Landmark");
            DropColumn("dbo.VendorsTravelandAccomodations", "Address");
            DropColumn("dbo.VendorsTravelandAccomodations", "name");
            DropColumn("dbo.VendorsPhotographies", "ZipCode");
            DropColumn("dbo.VendorsPhotographies", "State");
            DropColumn("dbo.VendorsPhotographies", "City");
            DropColumn("dbo.VendorsPhotographies", "Landmark");
            DropColumn("dbo.VendorsPhotographies", "Address");
            DropColumn("dbo.VendorsPhotographies", "name");
            DropColumn("dbo.VendorsOthers", "ZipCode");
            DropColumn("dbo.VendorsOthers", "State");
            DropColumn("dbo.VendorsOthers", "City");
            DropColumn("dbo.VendorsOthers", "Landmark");
            DropColumn("dbo.VendorsOthers", "Address");
            DropColumn("dbo.VendorsOthers", "name");
            DropColumn("dbo.VendorsInvitationCards", "ZipCode");
            DropColumn("dbo.VendorsInvitationCards", "State");
            DropColumn("dbo.VendorsInvitationCards", "City");
            DropColumn("dbo.VendorsInvitationCards", "Landmark");
            DropColumn("dbo.VendorsInvitationCards", "Address");
            DropColumn("dbo.VendorsInvitationCards", "name");
            DropColumn("dbo.VendorsGifts", "ZipCode");
            DropColumn("dbo.VendorsGifts", "State");
            DropColumn("dbo.VendorsGifts", "City");
            DropColumn("dbo.VendorsGifts", "Landmark");
            DropColumn("dbo.VendorsGifts", "Address");
            DropColumn("dbo.VendorsGifts", "name");
            DropColumn("dbo.VendorsEventOrganisers", "ZipCode");
            DropColumn("dbo.VendorsEventOrganisers", "State");
            DropColumn("dbo.VendorsEventOrganisers", "City");
            DropColumn("dbo.VendorsEventOrganisers", "Landmark");
            DropColumn("dbo.VendorsEventOrganisers", "Address");
            DropColumn("dbo.VendorsEventOrganisers", "name");
            DropColumn("dbo.VendorsEntertainments", "ZipCode");
            DropColumn("dbo.VendorsEntertainments", "State");
            DropColumn("dbo.VendorsEntertainments", "City");
            DropColumn("dbo.VendorsEntertainments", "Landmark");
            DropColumn("dbo.VendorsEntertainments", "Address");
            DropColumn("dbo.VendorsEntertainments", "name");
            DropColumn("dbo.VendorsDecorators", "ZipCode");
            DropColumn("dbo.VendorsDecorators", "State");
            DropColumn("dbo.VendorsDecorators", "City");
            DropColumn("dbo.VendorsDecorators", "Landmark");
            DropColumn("dbo.VendorsDecorators", "Address");
            DropColumn("dbo.VendorsDecorators", "name");
            DropColumn("dbo.VendorsCaterings", "ZipCode");
            DropColumn("dbo.VendorsCaterings", "State");
            DropColumn("dbo.VendorsCaterings", "City");
            DropColumn("dbo.VendorsCaterings", "Landmark");
            DropColumn("dbo.VendorsCaterings", "Address");
            DropColumn("dbo.VendorsCaterings", "name");
            DropColumn("dbo.VendorsBeautyServices", "ZipCode");
            DropColumn("dbo.VendorsBeautyServices", "State");
            DropColumn("dbo.VendorsBeautyServices", "City");
            DropColumn("dbo.VendorsBeautyServices", "Landmark");
            DropColumn("dbo.VendorsBeautyServices", "Address");
            DropColumn("dbo.VendorsBeautyServices", "name");
        }
    }
}
