// <auto-generated />
namespace MaaAahwanam.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrations_date_01192017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrations_date_01192017));
        
        string IMigrationMetadata.Id
        {
            get { return "201701191144425_migrations_date_01192017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
